name: Django CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

  # services:
  #   postgres:
  #     image: postgres: 13
  #     env:
  #       POSTGRES_USER: user
  #       POSTGRES_PASSWORD: password
  #       POSTGRES_DB: test_db
  #     ports:
  #       - 5432:5432
      
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install - requirements.txt
        
      # - name: Run Django migrations
      #   env: 
      #     DATABASE_URL: postgres://user:password@localhost:5432/test_db
      #   run: python manage.py migrate

      - name: Run tests
        run: python manage.py test


  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository 
  #       uses: actions/checkout@v3

  #     - name: Deploy to server
  #       run: |
  #         echo "Deploying application..."
  #           # Add your deployment steps here (e.g., SSH to server, copy files, restar
        
